/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.PostulantesJpaController;

import Modelo.Postulantes;
import com.placeholder.PlaceHolder;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Ismael
 */
public class ListaPostulantes extends javax.swing.JFrame {
    
    private PostulantesJpaController cn = new PostulantesJpaController();
    
    private DefaultTableModel dm;

    /**
     * Creates new form ListaEmpresa
     */
    public ListaPostulantes() {
        initComponents();
        PlaceHolder holder = new PlaceHolder(txtBusquedaNombre, "Buscar por Nombre");
        CrearModelo();
        llenarTabla();
        popUpMenu();
        setLocationRelativeTo(null);
        
        totalEmpresas();
    }

    //menu popUp para editar y eliminar empresa de la tabla
    public void popUpMenu() {
        JPopupMenu popup = new JPopupMenu();
        Icon ico = new ImageIcon(getClass().getResource("/Imagenes/icons8-lápiz-30.png"));
        JMenuItem menu1 = new JMenuItem("Editar Postulante", ico);

        //CODIGO PARA MANDAR LOS DATOS DE LA JTABLE AL FRAME DE EDITAR ATRAVEZ DE JPOPUP
        menu1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                editarPostulantes();
//                int fila = jTablePostulantes.getSelectedRow();
//
//                EditarPostulantes edit = new EditarPostulantes();
//
//                edit.txtIDEdit.setText(jTablePostulantes.getValueAt(fila, 0).toString());
//                edit.txtEditNombre.setText(jTablePostulantes.getValueAt(fila, 1).toString());
//                edit.txtEditApellido.setText(jTablePostulantes.getValueAt(fila, 2).toString());
//                edit.txtEditEdad.setText(jTablePostulantes.getValueAt(fila, 3).toString());
//                edit.txtEditDNI.setText(jTablePostulantes.getValueAt(fila, 4).toString());
//                edit.txtEditMovilidad.setText(jTablePostulantes.getValueAt(fila, 5).toString());
//                edit.txtEditNivelEducativo.setText(jTablePostulantes.getValueAt(fila, 6).toString());
//                edit.txtEditPerfil.setText(jTablePostulantes.getValueAt(fila, 7).toString());
//                edit.boxEditSexo.setSelectedItem(jTablePostulantes.getValueAt(fila, 8).toString());
//                edit.txtEditCuil.setText(jTablePostulantes.getValueAt(fila, 9).toString());
//                edit.txtEditDomicilio.setText(jTablePostulantes.getValueAt(fila, 10).toString());
//                edit.txtEditTelfPrincipal.setText(jTablePostulantes.getValueAt(fila, 11).toString());
//                edit.txtEditTelfAlternativo.setText(jTablePostulantes.getValueAt(fila, 12).toString());
//                edit.txtEditEmail.setText(jTablePostulantes.getValueAt(fila, 13).toString());
//                edit.txtEditDispHoraria.setText(jTablePostulantes.getValueAt(fila, 14).toString());
//                edit.jTextEditArea1.setText(jTablePostulantes.getValueAt(fila, 15).toString());
//
//                edit.setVisible(true);

            }
        });
        popup.add(menu1);
        
        jTablePostulantes.setComponentPopupMenu(popup);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePostulantes = new javax.swing.JTable();
        btnAgregarPostulante = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        labelTotalEmpresas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtBusquedaNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(197, 164, 59));

        jTablePostulantes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTablePostulantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTablePostulantes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTablePostulantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePostulantesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePostulantes);

        btnAgregarPostulante.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarPostulante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-agregar-propiedad-64.png"))); // NOI18N
        btnAgregarPostulante.setText("Agregar Postulante");
        btnAgregarPostulante.setBorderPainted(false);
        btnAgregarPostulante.setContentAreaFilled(false);
        btnAgregarPostulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPostulanteActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-volver-64_1.png"))); // NOI18N
        btnVolver.setText("Volver Al Menu");
        btnVolver.setBorderPainted(false);
        btnVolver.setContentAreaFilled(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        labelTotalEmpresas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar :");

        txtBusquedaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelTotalEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 607, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarPostulante)
                        .addGap(48, 48, 48)))
                .addComponent(btnVolver)
                .addContainerGap())
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(txtBusquedaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusquedaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTotalEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarPostulante)
                    .addComponent(btnVolver))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPostulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPostulanteActionPerformed
        dispose();
        new AgregarPostulantes().setVisible(true);
    }//GEN-LAST:event_btnAgregarPostulanteActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jTablePostulantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePostulantesMouseClicked

    }//GEN-LAST:event_jTablePostulantesMouseClicked

    private void txtBusquedaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaNombreActionPerformed
        filtro(txtBusquedaNombre.getText().trim(), jTablePostulantes);
    }//GEN-LAST:event_txtBusquedaNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaPostulantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaPostulantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaPostulantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaPostulantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaPostulantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPostulante;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePostulantes;
    private javax.swing.JLabel labelTotalEmpresas;
    private javax.swing.JTextField txtBusquedaNombre;
    // End of variables declaration//GEN-END:variables

    //Muestra la cantidad de empresas encontradas en la base de datos
    private void totalEmpresas() {
        labelTotalEmpresas.setText("Total De Postulantes Encontrados :  " + jTablePostulantes.getRowCount());
    }
    
    private void filtro(String consulta, JTable jtableBuscar) {
        dm = (DefaultTableModel) jtableBuscar.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(dm);
        jtableBuscar.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(consulta));
    }
    DefaultTableModel modelo;
    
    private void CrearModelo() {
        try {
            modelo = (new DefaultTableModel(
                    null, new String[]{
                        "ID", "Nombre",
                        "Apellido", "Edad", "DNI", "Movilidad", "Nv.Educativo",
                        "Sexo", "Perfil", "CUIL", "Domicilio", "Cel.Principal", "Cel.Alternativo", "E-Mail", "Disp.Horaria", "Notas"}) {
                Class[] types = new Class[]{
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,};
                boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false, false, false, false,
                    false, false, false, false, false, false, false, false
                };
                
                @Override
                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }
                
                @Override
                public boolean isCellEditable(int rowIndex, int colIndex) {
                    return canEdit[colIndex];
                }
                
            });
            jTablePostulantes.setModel(modelo);
            jTablePostulantes.getColumnModel().getColumn(0).setMaxWidth(30);
            jTablePostulantes.setRowHeight(30);
            jTablePostulantes.getTableHeader().setResizingAllowed(true);
            jTablePostulantes.getTableHeader().setReorderingAllowed(false);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString() + "error");
        }
    }
    
    private void llenarTabla() {
        try {
            Object A[] = null;
            List<Postulantes> Lista;
            Lista = cn.findPostulantesEntities();
            
            String[] datosPostulantes = new String[16];
            for (Postulantes p : Lista) {
                datosPostulantes[0] = p.getIdPostulantes().toString();
                datosPostulantes[1] = p.getNombre();
                datosPostulantes[2] = p.getApellido();
                datosPostulantes[3] = p.getEdad();
                datosPostulantes[4] = p.getDni();
                datosPostulantes[5] = p.getMovilidad();
                datosPostulantes[6] = p.getNivelEducativo();
                datosPostulantes[7] = p.getPerfil();
                datosPostulantes[8] = p.getSexo();
                datosPostulantes[9] = p.getCuil();
                datosPostulantes[10] = p.getDomicilio();
                datosPostulantes[11] = p.getTelfPrincipal();
                datosPostulantes[12] = p.getTelfAlternativo();
                datosPostulantes[13] = p.getEmail();
                datosPostulantes[14] = p.getDispHoraria();
                datosPostulantes[15] = p.getOtraInfo();
                
                modelo.addRow(datosPostulantes);
            }
            jTablePostulantes.setModel(modelo);
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    public void editarPostulantes() {
        int fila = jTablePostulantes.getSelectedRow();
        Postulantes postulante = new Postulantes(Integer.valueOf((String) jTablePostulantes.getValueAt(fila, 0)), jTablePostulantes.getValueAt(fila, 1).toString(),
                jTablePostulantes.getValueAt(fila, 2).toString(), jTablePostulantes.getValueAt(fila, 3).toString(),
                jTablePostulantes.getValueAt(fila, 4).toString(), jTablePostulantes.getValueAt(fila, 5).toString(),
                jTablePostulantes.getValueAt(fila, 6).toString(), jTablePostulantes.getValueAt(fila, 7).toString(),
                jTablePostulantes.getValueAt(fila, 8).toString(), jTablePostulantes.getValueAt(fila, 9).toString(),
                jTablePostulantes.getValueAt(fila, 10).toString(), jTablePostulantes.getValueAt(fila, 11).toString(),
                jTablePostulantes.getValueAt(fila, 12).toString(), jTablePostulantes.getValueAt(fila, 13).toString(),
                jTablePostulantes.getValueAt(fila, 14).toString(), jTablePostulantes.getValueAt(fila, 15).toString());
        EditarPostulantes edit = new EditarPostulantes(postulante);
        edit.setVisible(true);
    }
}
