
package Vista;


import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author Ismael
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        
    }
    
    public void paintComponent (Graphics g){
        Dimension tamanio  = getSize();
        ImageIcon fondo = new ImageIcon(getClass().getResource("/Imagenes/\"/Imagenes/icons8-lápiz-30.png\""));
        g.drawImage(fondo.getImage(),0,0,tamanio.width,tamanio.height,null);
        super.paintComponents(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        menuItemEmpresas = new javax.swing.JMenuItem();
        menuItemPostulantes = new javax.swing.JMenuItem();
        menuItemCursos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuItemCerrarSesion = new javax.swing.JMenuItem();
        menuItemSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemAcercaDe = new javax.swing.JMenuItem();

        jMenuItem4.setText("Cerrar Sesion");
        jPopupMenu1.add(jMenuItem4);

        jMenuItem6.setText("Ajustes De Usuario");
        jPopupMenu1.add(jMenuItem6);

        jMenuItem5.setText("Salir");
        jPopupMenu1.add(jMenuItem5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Oficina De Empleo Lujan De Cuyo");
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Marca_lujan_r.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 610, 220));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-usuario-de-género-neutro-80.png"))); // NOI18N
        jLabel3.setText("GUEST");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 500, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Gold BackGround.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu3.setText("Menu");

        menuItemEmpresas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-organización-30.png"))); // NOI18N
        menuItemEmpresas.setText("Gestor Empresas");
        menuItemEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEmpresasActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemEmpresas);

        menuItemPostulantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-llamada-de-conferencia-30.png"))); // NOI18N
        menuItemPostulantes.setText("Gestor Postulantes");
        menuItemPostulantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPostulantesActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemPostulantes);

        menuItemCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-gorro-de-graduación-30.png"))); // NOI18N
        menuItemCursos.setText("Gestor Cursos");
        menuItemCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCursosActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemCursos);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Ajustes");

        menuItemCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-exportar-30.png"))); // NOI18N
        menuItemCerrarSesion.setText("Cerrar Sesion");
        menuItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCerrarSesionActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemCerrarSesion);

        menuItemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-apagar-30_1.png"))); // NOI18N
        menuItemSalir.setText("Salir");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        menuItemAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-acerca-de-30.png"))); // NOI18N
        menuItemAcercaDe.setText("Acerca De");
        menuItemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAcercaDeActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemAcercaDe);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCerrarSesionActionPerformed
        new LogIn().setVisible(true);
        dispose();
    }//GEN-LAST:event_menuItemCerrarSesionActionPerformed

    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemSalirActionPerformed

    private void menuItemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAcercaDeActionPerformed
        new AcercaDe().setVisible(true);
    }//GEN-LAST:event_menuItemAcercaDeActionPerformed

    private void menuItemEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEmpresasActionPerformed
        dispose();        
        new ListaEmpresa().setVisible(true);
    }//GEN-LAST:event_menuItemEmpresasActionPerformed

    private void menuItemCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCursosActionPerformed
        dispose();
        new ListaCursos().setVisible(true);
    }//GEN-LAST:event_menuItemCursosActionPerformed

    private void menuItemPostulantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPostulantesActionPerformed
       dispose();
       new ListaPostulantes().setVisible(true);
    }//GEN-LAST:event_menuItemPostulantesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenuItem menuItemAcercaDe;
    private javax.swing.JMenuItem menuItemCerrarSesion;
    private javax.swing.JMenuItem menuItemCursos;
    private javax.swing.JMenuItem menuItemEmpresas;
    private javax.swing.JMenuItem menuItemPostulantes;
    private javax.swing.JMenuItem menuItemSalir;
    // End of variables declaration//GEN-END:variables
}
